<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Loops (Need) Exercises</span></div>

In [ ]:
Exercise 1 (Celsius to Fahrenheit) ☻

You are provided with the following list of temperatures in Celsius. Write a quick Python snippet that converts each temperature to Fahrenheit and prints both temperatures as a Celsius, Fahrenheit pair.

temperatures_celsius = [
    0, 5, 10, 15, 20, 25,
    30, 35, 40, 45, 50
]

In [1]:
temperatures_celsius = [
    0, 5, 10, 15, 20, 25,
    30, 35, 40, 45, 50
]

In [2]:
import numpy as np

In [3]:
c = np.array(temperatures_celsius)

In [4]:
type(temperatures_celsius)

list

In [16]:
f= c * 9/5 + 32

In [17]:
f

array([ 32.,  41.,  50.,  59.,  68.,  77.,  86.,  95., 104., 113., 122.])

In [18]:
for fahrenheit in f:
    print(f"{fahrenheit} pls work")

32.0 pls work
41.0 pls work
50.0 pls work
59.0 pls work
68.0 pls work
77.0 pls work
86.0 pls work
95.0 pls work
104.0 pls work
113.0 pls work
122.0 pls work


In [21]:
for fahrenheit, celcius in enumerate(temperatures_celsius):
    print(f'{fahrenheit} : {celcius}')

0 : 0
1 : 5
2 : 10
3 : 15
4 : 20
5 : 25
6 : 30
7 : 35
8 : 40
9 : 45
10 : 50


## EXERCISE 2

In [ ]:
Exercise 2 (Multiplication table) ☻

Example
Task
You can put a loop within a loop to do doubly loopy stuff. Here is an example:

for letter in ['A', 'B', 'C']:
    for number in [1, 2, 3]:
        print(f'{letter}{number}', end='\t')
    print('\n')

A1  A2  A3  

B1  B2  B3  

C1  C2  C3  
Try this out and explore.

In [22]:
for letter in ['A', 'B', 'C']:
    for number in [1, 2, 3]:
        print(f'{letter}{number}', end='\t')
    print('\n')

A1	A2	A3	

B1	B2	B3	

C1	C2	C3	



In [ ]:
Write a Python snippet that prints a multiplication table (up to 5) for numbers 1 through 5 using nested for loops. The output should be formatted as shown below:

1 : 1   2   3   4   5   
2 : 2   4   6   8   10  
3 : 3   6   9   12  15  
4 : 4   8   12  16  20  
5 : 5   10  15  20  25  

In [28]:
for number in [1,2,3,4,5]: # answer
    for number2 in [1,2,3,4,5]:
        print(f'{number * number2}', end = '\t') # what does this do
    print('\n') # what does this do

1	2	3	4	5	

2	4	6	8	10	

3	6	9	12	15	

4	8	12	16	20	

5	10	15	20	25	



## exercise 3

In [ ]:
Exercise 3 (Simulating a Coin Flip Experiment)  

Example
Task
Let’s use NumPy to simulate a simple experiment. NumPy has a random module that allows us to generate random numbers. We can generate 10 numbers between 0 and 1 by:

np.random.rand(10)

array([0.87820881, 0.51408832, 0.5028915 , 0.59833137, 0.76499243,
       0.40666847, 0.58407205, 0.00879205, 0.54712811, 0.95816881])
We can use this to simulate coin flips of a fair coin by considering values less than 0.5 as tails and values greater than 0.5 as heads. For example, in the above ‘experiment’ we have 8(!) heads.

In [29]:
np.random.rand(10)

array([0.86629453, 0.08863468, 0.37625122, 0.63963976, 0.74732307,
       0.56189939, 0.691126  , 0.80349803, 0.21531468, 0.06952895])

In [37]:
if np.random.rand(10) < 0.5:
    print(tails)
elif np.random.rand(10) == 0.5:
    print(tails)
else: print(heads)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [34]:
print(coinflip)

[0.45353338 0.14366171 0.73762055 0.84141486 0.88809686 0.51311509
 0.67009236 0.82679448 0.89331668 0.68877251]


In [ ]:
Using a for loop, run this experiment 10 times and, for each iteration, print out the number of heads.

Your results should look something like:

Experiment  1: No. of Heads = 4
Experiment  2: No. of Heads = 2
Experiment  3: No. of Heads = 8
Experiment  4: No. of Heads = 5
Experiment  5: No. of Heads = 8
Experiment  6: No. of Heads = 5
Experiment  7: No. of Heads = 4
Experiment  8: No. of Heads = 6
Experiment  9: No. of Heads = 2
Experiment 10: No. of Heads = 4
Note that your numbers will not be the same as mine, because the numbers are meant to be random!