<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

Subsetting: selecting desired elements from a dataset.

Indexing: labelling a singular element (eg, [1], [2]), which allows one to access it later on using the corresponding numbers.

Slicing: Separating a selected portion (usually a range) and labelling it to access later on.

Masking: Selecting a true/false array, labelling it to access later on. 

## exercise 2

In [8]:
Exercise 2 (Show me the ‘odd’ letters) ☻

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

Use masking to subset the letters that correspond to the odd numbers. I.e., get the result [A, C, E, G, I].

This is a slightly tricky problem because arrays are fussy about type. So, let me give you a recipe to solve this problem.

Subset all the first elements.
You should get array(['1', '3', '2', ..., '10', '9'])
Convert this to integers using astype(int)
You must look up how astype() works.
Use % to get the remainder for division by 2.
You should get array([1, 1, 0, ..., 0, 1]).
Use the previous result to create a mask that checks if the remainder is zero or not
You should get array([True, True, False, ..., False, True]).
Now you have identified the locations of the odd numbers.
Use the mask and extract the corresponding second elements.

SyntaxError: invalid character '‘' (U+2018) (743753084.py, line 1)

In [9]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [1]:
import numpy as np

TypeError: 'list' object is not callable

In [2]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [85]:
print(type(np_array_2d))  

<class 'numpy.ndarray'>


In [86]:
print(type(np_array_2d[:, 0]))  


<class 'numpy.ndarray'>


In [87]:
np_array_2d[:, 0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [88]:
numbers = np_array_2d[:,0]

In [89]:
numbers.astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [90]:
type(numbers)

numpy.ndarray

In [91]:
plswork = numbers.astype(int)

In [92]:
yeswork = plswork % 2

In [93]:
omgwork = yeswork == 1

In [94]:
np_array_2d[omgwork][:,1] # does this count

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

### condensed version

In [92]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
numbers = np_array_2d[:,0]
numbers.astype(int)
plswork = numbers.astype(int)
yeswork = plswork % 2
omgwork = yeswork == 1
np_array_2d[omgwork][:,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

## Exercise 3

In [7]:
Exercise 3  

[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

Consider the 2D array shown above. Using your knowledge of NumPy masking, change:

values below 50 to -1,
values above 50 to +1, and
values equal to 50 to 0.
You should end up with:

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]

SyntaxError: invalid decimal literal (1228899159.py, line 9)

In [91]:
 list2D = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

In [11]:
ummm = np.array(list2D)

In [36]:
morethan50 = ummm>50

In [42]:
morethan50 = morethan50 *1

In [68]:
morethan50

array([[1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [1, 0, 1, 0, 1]])

In [43]:
lessthan50 = ummm<50

In [47]:
lessthan50 = lessthan50 *-1

In [48]:
lessthan50

array([[ 0,  0,  0, -1, -1],
       [ 0, -1,  0, -1, -1],
       [ 0, -1, -1,  0, -1],
       [-1,  0,  0, -1, -1],
       [ 0, -1,  0, -1,  0]])

In [49]:
equalto50 = ummm==50

In [83]:
equalto50 = equalto50 * 0

In [89]:
ans = morethan50 + lessthan50 + equalto50

In [90]:
ans # final answer

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])

In [79]:
list1 =[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

In [80]:
for i in range(len(list1)): # manual way to change. using a 4 loop to go through the entire list within list, using if elif else conditions to set what you want to change.
    for j in range(len(list1[0])):
        if list1[i][j] > 50:
            list1[i][j] = 1
        elif list1[i][j] < 50:
            list1[i][j] = -1
        else:
            list1[i][j] = 0

In [81]:
list1

[[1, 0, 1, -1, -1],
 [1, -1, 1, -1, -1],
 [1, -1, -1, 1, -1],
 [-1, 1, 1, -1, -1],
 [1, -1, 1, -1, 1]]

In [57]:
type(lessthan50)

numpy.ndarray

In [32]:
if my_mask :
    print(np.array(-1))
else: print(np.array)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [34]:
my_mask = my_mask * 1


In [35]:
my_mask

array([[0, 0, 0, 1, 1],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 1, 0, 1, 0]])