<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [ ]:
list = [1,2,3,4,5]. # never use list as a variable, because it is a function

In [1]:
py_list= [1,2,3,4,5]

In [ ]:
list() # nooooooo!!

In [2]:
import numpy as np

In [6]:
py_list= [1,2,3,4,5]

In [7]:
np_array = np.array(py_list)

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

In [ ]:
py_list= [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])

In [ ]:
py_list + 1 # noo use np


In [8]:
py_list*2 #give two copies of the list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [9]:
np_array*2 #give values of list times two

array([ 2,  4,  6,  8, 10])

In [10]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [ ]:
if you wann achnage py_list, do this: py_list=py_list*2

In [ ]:
py_list*=2 # is faster

In [11]:
len(np_array)

5

In [12]:
np_array.shape

(5,)

## 1.3 Accessing data from a dictionary

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

## 2.1 Size

In [13]:
len(np_array)

5

In [14]:
np_array.shape

(5,)

## 2.2 Arrays are fussy about type

In [15]:
'a' in ['a','b','c']

True

In [18]:
np.random.randint(0,100,100)

array([62, 39, 56, 70, 64, 24, 46, 40,  8, 93, 34, 58, 18, 61, 76, 73, 36,
       63,  2, 38, 40, 83,  0,  8, 89, 44, 31, 70, 68, 39, 32, 80, 39, 98,
       90, 30, 14, 73, 65, 16, 43, 91, 73, 81, 95, 48, 85, 32, 50, 67,  0,
        7, 92, 46, 91, 20, 32, 15, 40,  1,  1,  2, 79, 54, 65,  2, 72, 71,
       46, 32, 74, 14,  2, 72, 97, 18, 44, 73, 84, 60, 14, 29, 24, 31, 68,
       78, 33, 65, 79, 71, 60, 20, 40, 43, 53, 98, 78, 93, 20, 42])

In [19]:
my_rand_numbers= np.random.randint(0,100,100)

In [20]:
my_rand_numbers < 50

array([False,  True, False,  True, False, False,  True, False,  True,
        True, False,  True, False,  True,  True, False,  True, False,
        True, False,  True, False, False,  True,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True, False,  True,  True,
       False, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
        True, False, False,  True,  True, False, False,  True, False,
        True,  True, False, False, False, False,  True, False, False,
        True])

In [22]:
mask = my_rand_numbers < 50

In [23]:
my_rand_numbers[mask]

array([17, 24, 26, 41, 22, 31, 32, 27, 16, 35, 29, 33, 23, 20, 15, 24, 37,
       43, 27, 23, 33, 26,  2, 29, 33, 11, 17, 17, 15, 38,  3,  1, 35, 13,
       39, 39,  3, 46, 17, 21, 47, 43, 12, 29, 32,  4, 45, 44,  0, 26, 29])

In [ ]:
(my_rand_numbers%2==0)  # to find even numbers --> % yields the remainder when the first operand is divided by the second

In [ ]:
(my_rand_numbers%2==1) # to find odd

In [48]:
mask = (my_rand_numbers < 50) & (my_rand_numbers%2==0) #use and symbol to combine!!!

In [49]:
my_rand_numbers[mask] # [] is for elipse, masking and lists {} is for f string or dictionary

array([24, 26, 22, 32, 16, 20, 24, 26,  2, 38, 46, 12, 32,  4, 44,  0, 26])

In [50]:
mask = (my_rand_numbers < 50) | (my_rand_numbers%2==0) # or

In [51]:
my_rand_numbers[mask]

array([72, 17, 82, 24, 58, 26, 41, 22, 60, 31, 32, 27, 16, 35, 29, 88, 33,
       23, 20, 66, 96, 58, 15, 98, 90, 24, 86, 37, 43, 27, 68, 23, 33, 26,
       62,  2, 29, 33, 11, 17, 17, 15, 38, 72,  3,  1, 35, 76, 13, 39, 39,
       60, 62,  3, 46, 17, 21, 84, 47, 43, 12, 29, 74, 32,  4, 54, 90, 45,
       44,  0, 84, 72, 62, 76, 26, 70, 29])

In [34]:
my_rand_numbers

array([72, 17, 82, 24, 79, 58, 26, 81, 41, 22, 60, 31, 81, 32, 27, 71, 16,
       77, 35, 55, 29, 73, 88, 33, 23, 20, 66, 69, 67, 96, 58, 15, 98, 87,
       93, 55, 90, 24, 86, 37, 43, 27, 68, 23, 33, 26, 62,  2, 29, 33, 11,
       17, 17, 59, 15, 38, 72,  3,  1, 35, 76, 13, 39, 69, 59, 39, 60, 62,
        3, 46, 17, 21, 77, 84, 73, 79, 47, 43, 12, 87, 53, 29, 74, 57, 32,
        4, 54, 90, 45, 51, 44,  0, 84, 72, 62, 76, 26, 91, 70, 29])

In [35]:
my_rand_numbers[2] #finds number in the second position

np.int64(82)

## 2.3 Adding a number

## 2.4 Adding another list

In [ ]:
py_2d_list = [[1,2,3],[4,5,6],[7,8,9]]

In [37]:
py_2d_list[0]

[1, 2, 3]

In [38]:
py_2d_list = [[1, 'A'],[2,'B']]
np_2d_list = np.array(py_2d_list)

In [39]:
py_2d_list #py list allows multiple types 

[[1, 'A'], [2, 'B']]

In [40]:
np_2d_list #np arrays dont tolerate different types, 
#it only allows one type : optimised to do array operations, 
#if hv diff types of numbers it Will slow down, so it will create everything to the same type eg, 1 --> '1', 
#instead of just 1 in py_list

array([['1', 'A'],
       ['2', 'B']], dtype='<U21')

In [41]:
py_2d_list[0][1] #if you want just A

'A'

In [42]:
np_2d_list[0,]

np.str_('A')

In [52]:
py_2d_list[1:4]

[[2, 'B']]

In [53]:
np_2d_list[0:4,1] #comparing first pos of each list point

array(['A', 'B'], dtype='<U21')

In [55]:
np_2d_list[:,0].astype(int)**3

array([1, 8])

In [ ]:
py_list[3:6] #will give values in list frm 3rd to 6th pos

In [ ]:
py_list[-1::1] #last element to the end, last element inclusive

## 2.5 Multiplying by a Number

## 2.6 Squaring

## 2.7 Asking questions

## 2.8 Mathematics

# dictionary

In [44]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {
    "Natasha Romanoff": ["Black Widow", "Johannson"],
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [47]:
superhero_info['Natasha Romanoff']

['Black Widow', 'Johannson']

## Footnotes